### ISSUE TITLE
allow multiple roles for single clusters

### ISSUE THREAD

**Issue by karlderkaefer** [signavio/aws-mfa-login#11]
we want to assume different roles per cluster which would look like `~/.aws-mfa.yaml` so we can switch the role with `kubectx suite-staging` or `kubectx suite-staging-debug`
```yaml
source: suite
destination: mfa
clusters:
  # staging
  - name: eks-staging_eu
    alias: suite-staging
    accountId: "1234567890"
    role: DeveloperAccessRole
    region: eu-central-1
  - name: eks-staging_eu
    alias: suite-staging-debug
    accountId: "1234567890"
    role: DebugAccessRole
    region: eu-central-1
```
by default this is not possible with cli `aws eks update-kubeconfig` see this issue https://github.com/aws/aws-cli/pull/5413 and https://github.com/aws/aws-cli/issues/4079

So this means I would need to implement aws eks update-kubeconfig completly in golang unless this is not merged
